export const serializeUser = (user) => ({
  id: user._id,
  role: user.role || "user",
  firstName: user.firstName,
  email: user.email,
  phone: user.phone,
  gender: user.gender || null,
  age: user.age ?? null,
  weightCurrent: user.weightCurrent || null,
  goalWeight: user.goalWeight || null,
  height: user.height || null,
  fitnessGoals: user.fitnessGoals || [],
  mobilityType: user.mobilityType || null,
  mobilityTypeOther: user.mobilityTypeOther || null,
  fitnessExperience: user.fitnessExperience || null,
  onboardingStep: user.onboardingStep,
  onboardingCompleted: user.onboardingCompleted,
  selectedPlan: user.selectedPlan || null,
  subscriptionStatus: user.subscriptionStatus,
  trialActivatedAt: user.trialActivatedAt || null,
  trialEndsAt: user.trialEndsAt || null,
  subscriptionStartedAt: user.subscriptionStartedAt || null,
  subscriptionEndsAt: user.subscriptionEndsAt || null,
  lastLoginAt: user.lastLoginAt || null,
  createdAt: user.createdAt,
  updatedAt: user.updatedAt,
}); 
