import { toMediaUrl } from "./mediaResponse.js";

export const serializeUser = (user) => ({
  id: user._id,
  role: user.role || "user",
  firstName: user.firstName,
  lastName: user.lastName || "",
  email: user.email,
  phone: user.phone,
  bio: user.bio || "",
  preferredLanguage: user.preferredLanguage || "en",
  accessibilityPreferences: {
    largerText: Boolean(user.accessibilityPreferences?.largerText),
    highContrast: Boolean(user.accessibilityPreferences?.highContrast),
    reducedMotion: Boolean(user.accessibilityPreferences?.reducedMotion),
    screenReaderOptimized: Boolean(user.accessibilityPreferences?.screenReaderOptimized),
  },
  profileImage: toMediaUrl(user.profileImage),
  gender: user.gender || null,
  age: user.age ?? null,
  weightCurrent: user.weightCurrent || null,
  goalWeight: user.goalWeight || null,
  height: user.height || null,
  fitnessGoals: user.fitnessGoals || [],
  mobilityType: user.mobilityType || null,
  mobilityTypeOther: user.mobilityTypeOther || null,
  fitnessExperience: user.fitnessExperience || null,
  onboardingStep: user.onboardingStep,
  onboardingCompleted: user.onboardingCompleted,
  selectedPlan: user.selectedPlan || null,
  subscriptionStatus: user.subscriptionStatus,
  trialActivatedAt: user.trialActivatedAt || null,
  trialEndsAt: user.trialEndsAt || null,
  subscriptionStartedAt: user.subscriptionStartedAt || null,
  subscriptionEndsAt: user.subscriptionEndsAt || null,
  lastLoginAt: user.lastLoginAt || null,
  accountStatus: user.accountStatus || (user.isActive ? "active" : "deactivated"),
  isActive: Boolean(user.isActive),
  createdAt: user.createdAt,
  updatedAt: user.updatedAt,
}); 
